/*
W3C Testable Statements Generator 1.0
Authored by Bryan Garaventa
Distributed under the terms of the Open Source Initiative OSI - MIT License

INSTRUCTIONS

To run, click the file named "StartGeneratingStatements.bat".

All testable statements will automatically be generated from sUrl, and saved as HTML files within the folder docs\Autogenerated AccName 1.1 Testable Statements - W3C.

An index.html file will be saved to the same output folder so that all testable statements can be accessed from one page.
*/

var sUrl = "https://www.w3.org/wiki/AccName_1.1_Testable_Statements";

var wS = new ActiveXObject("WScript.Shell");
var sF = wS.CurrentDirectory;
var hJ = sF + "\\HomerJax\\HomerJax.wsc";
var tTemplate = sF + "\\TestTemplate.txt";
var iTemplate = sF + "\\IndexTemplate.txt";
var tFolder = sF + "\\..\\docs\\Autogenerated AccName 1.1 Testable Statements - W3C\\";
var oJax = GetObject("script:" + hJ);

var domObj = oJax.VtCreateHtmlFile();
var html = oJax.WebRequestGetToString(sUrl);
domObj.write(html);

var subNode = domObj.getElementById("mw-content-text");
var curNode = subNode.firstChild;
var tests = {};
var name = "";

while (curNode) {
	if (curNode.nodeType === 1 && curNode.nodeName.toLowerCase() == "h3") {
		name = curNode.innerText || "";
		name = name.replace(/[\\/:*?""<>|]/, " ").replace(/\s+/g, " ").replace(/^\s+|\s+$/g, "");
	}
	else if (name !== "" && curNode.nodeType === 1 && curNode.nodeName.toLowerCase() == "pre") {
		var test = curNode.innerText || "";
		tests[name] = test.replace(/^[^<]*</, "<").replace(/>[^>]*$/, ">");
		name = "";
	}
	curNode = curNode.nextSibling;
}

tTemplate = oJax.FileToString(tTemplate);
iTemplate = oJax.FileToString(iTemplate);
var links = [];

for (name in tests) {
	var t = tTemplate.replace("[[TestStatementCodeName]]", name).replace("[[TestStatementCodeBlock]]", tests[name]);
	oJax.StringToFile(t, tFolder + name + ".html");
	links.push("<a href=\"" + name + ".html" + "\">" + name + "</a>");
}

var t = iTemplate.replace("[[TestStatementCodeList]]", links.join("\n</li><li>\n"));
oJax.StringToFile(t, tFolder + "index.html");

oJax.DialogShow("Result", "Number of testable statements generated: " + links.length);